MULTI_SPEECH_SEPERATION_MODELS = ("demucs", "conv-tasnet")
MULTI_CHANNEL_SEPERATION_MODELS = ("demucs", "conv-tasnet", "unet")
MONARCH_SPEECH_SEPARTAION_MODELS = ("mel-rnn", "dcunet", "crn", "dnn", "unet", "dccrn", "wav-unet")
STFT_MODELS = ("mel-rnn", "dcunet", "crn", "dnn", "unet")
WAV_MODELS = ("dccrn", "demucs", "conv-tasnet", "wav-unet")