path:
  # root: # [TODO] set clairty challenge dataset path
  root: ''
  metadata_dir: ${path.root}/clarity_data/metadata
  scenes_listeners_file: ${path.metadata_dir}/scenes_listeners.dev.json
  listeners_file: ${path.metadata_dir}/listeners.json
  scenes_folder: ${path.root}/clarity_data/dev/scenes
  exp_folder: ./exp # folder to store enhanced signals and final results


nalr:
  nfir: 220
  fs: 44100

compressor:
  threshold: 0.35
  attenuation: 0.1
  attack: 50
  release: 1000
  rms_buffer_size: 0.064

soft_clip: True

evaluate:
  set_random_seed: True
  small_test: True

# hydra config
hydra:
  run:
    dir: ${path.exp_folder}
